routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\CompteController;
use App\Http\Controllers\AgenceController;
use App\Http\Controllers\OperationController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientHomeController;
use App\Http\Controllers\DashboardController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group([
  'middleware' => 'auth',
  'prefix' => '/app',
], function(){
  Route::get('/', [DashboardController::class, 'home'])->name("dashboard");
  // Pages client
  Route::group([
    'prefix' => '/client',
    'middleware' => 'has.role:client',
  ], function(){
    Route::get('/comptes', [ClientHomeController::class, 'comptes'])->name("list-comptes-client");
    Route::get('/operations', [ClientHomeController::class, 'operations'])->name("list-operations-client");

    // Route::group(['middleware' => "has.role:gerant|gerant_adjoint"], function(){
    //   Route::get('/add', [CompteController::class, 'create'])->name("create-compte");
    //   Route::post('/add', [CompteController::class, 'store']);
    //   Route::get('/{compte}', [CompteController::class, 'show'])->name("show-compte");
    //   Route::get('/{compte}/edit', [CompteController::class, 'edit'])->name("edit-compte");
    //   Route::post('/{compte}/edit', [CompteController::class, 'update']);
    //   Route::post('/{compte}/delete', [CompteController::class, 'destroy'])->name("delete-compte");
    //   Route::get('/clients/json', [CompteController::class, 'jsonList'])->name("json-list-comptes");
    // });
  });
  // Clients
  Route::group([
    'prefix' => '/utilisateurs',
    'middleware' => 'has.role:gerant',
  ], function(){
    Route::get('/', [UserController::class, 'index'])->name("list-users");
    Route::get('/add', [UserController::class, 'create'])->name("create-user");
    Route::post('/add', [UserController::class, 'store']);
    Route::get('/{user}', [UserController::class, 'show'])->name("show-user");
    Route::get('/{user}/edit', [UserController::class, 'edit'])->name("edit-user");
    Route::post('/{user}/edit', [UserController::class, 'update']);
    Route::post('/{user}/delete', [UserController::class, 'destroy'])->name("delete-user");
  });
  // Clients
  Route::group([
    'prefix' => '/clients',
    'middleware' => 'has.role:gerant|gerant_adjoint',
  ], function(){
    Route::get('/', [ClientController::class, 'index'])->name("list-clients");
    Route::get('/add', [ClientController::class, 'create'])->name("create-client");
    Route::post('/add', [ClientController::class, 'store']);
    Route::get('/{client}', [ClientController::class, 'show'])->name("show-client");
    Route::get('/{client}/edit', [ClientController::class, 'edit'])->name("edit-client");
    Route::post('/{client}/edit', [ClientController::class, 'update']);
    Route::post('/{client}/delete', [ClientController::class, 'destroy'])->name("delete-client");
  });
  // Comptes
  Route::group(['prefix' => '/comptes'], function(){
    Route::get('/', [CompteController::class, 'index'])->name("list-comptes")->middleware("has.role:gerant|gerant_adjoint|caissiere");
    Route::group(['middleware' => "has.role:gerant|gerant_adjoint"], function(){
      Route::get('/add', [CompteController::class, 'create'])->name("create-compte");
      Route::post('/agios', [CompteController::class, 'agios'])->name("agios");
      Route::post('/add', [CompteController::class, 'store']);
      Route::get('/{compte}', [CompteController::class, 'show'])->name("show-compte");
      Route::get('/{compte}/edit', [CompteController::class, 'edit'])->name("edit-compte");
      Route::post('/{compte}/edit', [CompteController::class, 'update']);
      Route::post('/{compte}/delete', [CompteController::class, 'destroy'])->name("delete-compte");
      Route::post('/{compte}/freeze', [CompteController::class, 'freeze'])->name("freeze-compte");
      Route::get('/clients/json', [CompteController::class, 'jsonList'])->name("json-list-comptes");
    });
  });
  // Agences
  Route::group([
    'prefix' => '/agences',
    'middleware' => 'has.role:gerant',
  ], function(){
    Route::get('/', [AgenceController::class, 'index'])->name("list-agences");
    Route::get('/add', [AgenceController::class, 'create'])->name("create-agence");
    Route::post('/add', [AgenceController::class, 'store']);
    Route::get('/{agence}', [AgenceController::class, 'show'])->name("show-agence");
    Route::get('/{agence}/edit', [AgenceController::class, 'edit'])->name("edit-agence");
    Route::post('/{agence}/edit', [AgenceController::class, 'update']);
    Route::post('/{agence}/delete', [AgenceController::class, 'destroy'])->name("delete-agence");
  });
  // Operations
  Route::group(['prefix' => '/operations'], function(){
    Route::group(['middleware' => "has.role:gerant|gerant_adjoint|caissiere"], function(){
      Route::get('/', [OperationController::class, 'index'])->name('list-operations');
      Route::get('/{operation}', [OperationController::class, 'show'])->name('show-operation');
    });
    Route::group(['middleware' => 'has.role:caissiere'], function(){
      Route::get('/comptes/json', [OperationController::class, 'jsonComptes'])->name("json-comptes");
      // Depots
      Route::group(['prefix' => '/depots'], function(){
        // Route::get('/', [OperationController::class, 'listDeposits'])->name('list-depots');
        Route::get('/make', [OperationController::class, 'deposit'])->name('make-depot');
        Route::post('/make', [OperationController::class, 'storeDeposit']);
      });
      // Retraits
      Route::group(['prefix' => '/retraits'], function(){
        // Route::get('/', [OperationController::class, 'listWds'])->name('list-retraits');
        Route::get('/make', [OperationController::class, 'withdraw'])->name('make-retrait');
        Route::post('/make', [OperationController::class, 'storeWithdraw']);
      });
      // Transfert
      Route::group(['prefix' => '/transferts'], function(){
        // Route::get('/', [OperationController::class, 'listTransfers'])->name('list-transferts');
        Route::get('/make', [OperationController::class, 'transfer'])->name('make-transfert');
        Route::post('/make', [OperationController::class, 'storeTransfer']);
      });
    });

  });
});





require __DIR__.'/auth.php';

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;

    protected $fillable = [
      "cni",
      "nom",
      "prenom",
      "date_naissance",
      "profession",
      "telephone",
      "photo",
      "signature",
      "sexe_id",
    ];

    public function sexe()
    {
      return $this->belongsTo(Sexe::class);
    }

    public function getNomCompletAttribute()
    {
      return ucwords($this->prenom.' '.strtoupper($this->nom));
    }

    public function getPhotoPathAttribute()
    {
      return asset(empty($this->photo) ? '/assets/media/users/blank.png' : str_replace('public/', '', 'storage/'.$this->photo));
    }

    public function comptes()
    {
      return $this->hasMany(Compte::class, 'client_id');
    }

    public function getSoldeAttribute()
    {
      $solde = 0;
      foreach ($this->comptes as $cp) {
        $solde += $cp->solde;
      }

      return $solde;
    }

    public function user()
    {
      return $this->hasOne(User::class, 'client_id');
    }
}

app/Models/Compte.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Compte extends Model
{
    use HasFactory;

    protected $fillable = [
      "numero",
      "date_ouverture",
      "visa_ouverture",
      "date_fermeture",
      "visa_fermeture",
      "observation",
      "solde",
      "client_id",
    ];


    protected $casts = [
      "date_ouverture" => "datetime",
      "date_fermeture" => "datetime",
      "solde" => "double",
    ];


    public function client()
    {
      return $this->belongsTo(Client::class);
    }

    public function operations()
    {
      return $this->hasMany(Operation::class, 'compte_id');
    }

    public function calculate_total($type)
    {
      $t = 0;
      foreach ($this->operations->where('type_operation_id', $type) as $op) {
        $t += $op->montant;
      }
      return $t;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'matricule',
        'photo',
        'email',
        'password',
        'role',
        'active',
        'client_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'active' => "boolean",
    ];


    public function getPhotoPathAttribute()
    {
      return asset(empty($this->photo) ? '/assets/media/users/blank.png' : str_replace('public/', '', 'storage/photos/'.$this->photo));
    }

    public function getClientAttribute()
    {
      if($this->client_id)
        return $this->belongsTo(Client::class);
      else
        return Client::first(); // Remove this on Prod
    }
}

app/Http/Controllers/CompteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Compte;
use App\Models\Client;
use App\Models\Operation;
use Illuminate\Http\Request;
use App\Http\Requests\CompteCreateRequest;
use App\Http\Requests\CompteEditRequest;
use Yajra\DataTables\Facades\DataTables as FacadesDataTables;
use Carbon\Carbon;

class CompteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      if ($request->ajax()) {
        $model = Compte::query();
        return FacadesDataTables::eloquent($model->with(['client']))
        ->filter(function ($query) {
          if (request()->has('query.q')) {
            $query->where('numero', 'like', "%" . request('query.q') . "%")
            ->orWhere('observation', 'like', "%" . request('query.q') . "%");
          }
          if(request()->has('sort.field') && request()->has('sort.sort') && in_array(request('sort.field'), ["DT_RowIndex", "numero", "date_ouverture", "visa_ouverture", "date_fermeture", "visa_fermeture", "solde", "client", "created_at"]) && in_array(request('sort.sort'), ['asc', 'desc'])) {
            $cols = [
              "DT_RowIndex" => "id",
              "numero" => "numero",
              "date_ouverture" => "date_ouverture",
              "visa_ouverture" => "visa_ouverture",
              "date_fermeture" => "date_fermeture",
              "visa_fermeture" => "visa_fermeture",
              "solde" => "solde",
              "client" => "client_id",
              "created_at" => "created_at",
            ];
            $query->orderBy($cols[request("sort.field")], request("sort.sort"));
          } else {
            $query->orderByDesc('id');
          }
        }, true)
        ->addIndexColumn()
        ->editColumn('created_at', function (Compte $c) {
          return Carbon::parse($c->created_at)->locale('fr')->isoFormat("DD MMM YYYY, HH:mm");
        })
        ->editColumn('date_ouverture', function (Compte $c) {
          return Carbon::parse($c->date_ouverture)->locale('fr')->isoFormat("DD/MM/YYYY");
        })
        ->addColumn('action', function ($row) {
          return 'Edit/Delete';
        })
        ->toJson();
      }

      return view("contents.comptes.list", [
        'count' => Compte::count(),
      ]);
    }

    public function jsonList(Request $request)
    {
      return response()->json(
        Client::where('nom', 'like', "%" . request('q') . "%")
          ->orWhere('prenom', 'like', "%" . request('q') . "%")
          ->paginate(30),
      );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('contents.comptes.create', [
        'clients' => Client::all(),
      ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompteCreateRequest $request)
    {
        $input = $request->validated();
        $input['visa_ouverture'] = auth()->user()->name;
        Compte::create($input);

        return response()->json([
          'success' => true,
          'message' => "Le Compte a bien été crée.",
          // 'input' => $input,
          'redirect' => route('list-comptes'),
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Compte  $compte
     * @return \Illuminate\Http\Response
     */
    public function show(Compte $compte)
    {
      return view('contents.comptes.show', [
        'compte' => $compte,
      ]);
    }


    public function freeze(Compte $compte)
    {
      if(auth()->user()->role != 'gerant')
        abort(403);

      $compte->update([
        'date_fermeture' => $compte->date_fermeture ? null : date("Y-m-d H:i:s"),
        'visa_fermeture' => $compte->date_fermeture ? null : auth()->user()->name,
      ]);

      return redirect()->back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Compte  $compte
     * @return \Illuminate\Http\Response
     */
    public function edit(Compte $compte)
    {
      return view('contents.comptes.edit', [
        'clients' => Client::all(),
        'compte' => $compte,
      ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Compte  $compte
     * @return \Illuminate\Http\Response
     */
    public function update(CompteEditRequest $request, Compte $compte)
    {
      $input = $request->validated();
      $continue = $input['continue'] ?? route('show-compte', ['compte' => $compte->id]);
      unset($input['continue']);
      $compte->update($input);

      return response()->json([
        'success' => true,
        'message' => "Le Compte a bien été mis à jour.",
        // 'input' => $input,
        'redirect' => $continue,
      ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Compte  $compte
     * @return \Illuminate\Http\Response
     */
    public function destroy(Compte $compte)
    {
      $compte->delete();

      return redirect()->route('list-comptes');
    }



    public function agios()
    {
      $comptes = Compte::all();
      foreach ($comptes as $compte) {
        $compte->decrement("solde", 1000);
        Operation::create([
          "numero" => "011".str_pad(Operation::count()+1, 7, mt_rand(1000, 10000), STR_PAD_LEFT),
          "date" => date("Y-m-d H:i:s"),
          "montant" => 1000,
          "visa" => auth()->user()->name,
          "observation" => "Prélèvement mensuel AGIOS",
          "agence_id" => 1,
          "mode_operation_id" => 3,
          "type_operation_id" => 3,
          "compte_id" => $compte->id,
          "compte_dest_id" => null,
        ]);
      }

      return redirect()->back();
    }
}

resources/views/contents/comptes/edit.blade.php
@extends('layouts.dashboard')

@section('title')
  Compte {{ $compte->numero }}
@endsection

@section('content')
  <div class="d-flex flex-row flex-column-fluid container">
    <!--begin::Content Wrapper-->
    <div class="main d-flex flex-column flex-row-fluid">
      <!--begin::Subheader-->
      <div class="subheader py-2 py-lg-6" id="kt_subheader">
        <div class="w-100 d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
          <!--begin::Info-->
          <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
              <!--begin::Page Title-->
              <h5 class="text-dark font-weight-bold my-1 mr-5">Modifier le Compte {{ $compte->numero }}</h5>
              <!--end::Page Title-->
              <!--begin::Breadcrumb-->
              <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                <li class="breadcrumb-item">
                  <a href="{{ route('list-comptes') }}" class="text-muted">Comptes</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{{ route('show-compte', ['compte' => $compte->id]) }}" class="text-muted">{{ $compte->numero }}</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="{{ route('edit-compte', ['compte' => $compte->id]) }}" class="text-muted">Modifier</a>
                </li>
              </ul>
              <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
          </div>
          <!--end::Info-->
          <!--begin::Toolbar-->
          <div class="d-flex align-items-center">
            <a href="{{ url()->previous() }}" class="btn btn-light-primary font-weight-bolder">
              <span class="svg-icon svg-icon-md mr-1">
                <!--begin::Svg Icon | path:assets/media/svg/icons/Navigation/Left-2.svg-->
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                  <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <polygon points="0 0 24 0 24 24 0 24"></polygon>
                    <rect fill="#000000" opacity="0.3" transform="translate(15.000000, 12.000000) scale(-1, 1) rotate(-90.000000) translate(-15.000000, -12.000000)" x="14" y="7" width="2" height="10" rx="1"></rect>
                    <path d="M3.7071045,15.7071045 C3.3165802,16.0976288 2.68341522,16.0976288 2.29289093,15.7071045 C1.90236664,15.3165802 1.90236664,14.6834152 2.29289093,14.2928909 L8.29289093,8.29289093 C8.67146987,7.914312 9.28105631,7.90106637 9.67572234,8.26284357 L15.6757223,13.7628436 C16.0828413,14.136036 16.1103443,14.7686034 15.7371519,15.1757223 C15.3639594,15.5828413 14.7313921,15.6103443 14.3242731,15.2371519 L9.03007346,10.3841355 L3.7071045,15.7071045 Z" fill="#000000" fill-rule="nonzero" transform="translate(9.000001, 11.999997) scale(-1, -1) rotate(90.000000) translate(-9.000001, -11.999997)"></path>
                  </g>
                </svg>
                <!--end::Svg Icon-->
              </span>
              Retour
            </a>
          </div>
          <!--end::Toolbar-->
        </div>
      </div>
      <!--end::Subheader-->
      <div class="content flex-column-fluid" id="kt_content">
        <!--begin::Card-->
        <form method="post" action="{{ route('edit-compte', ['compte' => $compte->id]) }}" class="form-xhr form fv-plugins-bootstrap fv-plugins-framework" id="kt_form">
          @csrf
          <input type="hidden" name="continue" value="{{ url()->previous() }}">
          <div class="card card-custom card-shadowless rounded-top-0">
            <!--begin::Body-->
            <div class="card-body">
              <div class="row justify-content-center py-4 px-8 py-lg-8 px-lg-10">
                <div class="col-xl-12 col-xxl-10">
                  <div class="row justify-content-center">
                    <div class="col-xl-9">
                      <div class="my-5">
                        <h5 class="text-dark font-weight-bold mb-10">Détails du Compte :</h5>
                        <!--begin::Group-->
                        <div class="form-group row">
                          <label class="col-xl-3 col-lg-3 col-form-label text-left"></label>
                          <div class="col-lg-9 col-xl-9">
                            <div class="image-input image-input-outline" id="kt_user_add_avatar">
                              <div class="image-input-wrapper" style="background-image: url({{ $compte->client->photo_path }})"></div>
                          </div>
                        </div>
                      </div>
                      <!--end::Group-->
                      <!--begin::Group-->
                      <div class="form-group row fv-plugins-icon-container">
                        <label class="col-xl-3 col-lg-3 col-form-label">Client</label>
                        <div class="col-lg-9 col-xl-9">
                          <select class="form-control form-control-lg form-control-solid form-control-select custom-select select2" id="kt_select2_6"  name="client_id" id="select-client" disabled>
                            <option value="{{ $compte->client_id }}" selected>{{ $compte->client->nom_complet }}</option>
                          </select>
                          <div class="fv-plugins-message-container"></div>
                        </div>
                      </div>
                      <!--end::Group-->
                      <!--begin::Group-->
                      <div class="form-group row fv-plugins-icon-container">
                        <label class="col-xl-3 col-lg-3 col-form-label">Numéro du Compte</label>
                        <div class="col-lg-9 col-xl-9">
                          <input class="form-control form-control-solid form-control-lg" name="numero" type="text" value="{{ $compte->numero }}" readonly>
                          <div class="fv-plugins-message-container"></div>
                        </div>
                      </div>
                      <!--end::Group-->
                      <!--begin::Group-->
                      <div class="form-group row fv-plugins-icon-container">
                        <label class="col-xl-3 col-lg-3 col-form-label">Date d'ouverture</label>
                        <div class="col-lg-9 col-xl-9">
                          <input type="text" name="date_ouverture" class="form-control form-control-lg form-control-solid" id="dob" readonly="readonly" value="{{ date("Y-m-d", strtotime($compte->date_ouverture)) }}">
                          <div class="fv-plugins-message-container"></div>
                        </div>
                      </div>
                      <!--end::Group-->
                      <!--begin::Group-->
                      <div class="form-group row fv-plugins-icon-container">
                        <label class="col-xl-3 col-lg-3 col-form-label">Solde d'ouverture</label>
                        <div class="col-lg-9 col-xl-9">
                          <input class="form-control form-control-solid form-control-lg" name="solde" type="number" min="0" value="{{ $compte->solde }}">
                          <div class="fv-plugins-message-container"></div>
                        </div>
                      </div>
                      <!--end::Group-->
                      <!--begin::Group-->
                      <div class="form-group row fv-plugins-icon-container">
                        <label class="col-xl-3 col-lg-3 col-form-label">Observation</label>
                        <div class="col-lg-9 col-xl-9">
                          <textarea name="observation" rows="4" class="form-control form-control-solid form-control-lg form-control-textarea" id="observation">{{ $compte->observation }}</textarea>
                          <div class="fv-plugins-message-container"></div>
                        </div>
                      </div>
                      <!--end::Group-->
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--end::Body-->
          <!--begin::Actions-->
          <div class="card-footer">
            <div class="row justify-content-center px-8 px-lg-10">
              <div class="col-xl-12 col-xxl-10">
                <div class="row justify-content-center">
                  <div class="col-xl-6">
                    <button type="submit" class="submitter btn-lg btn btn-primary font-weight-bold mr-2" id="kt_btn_spinner">Enregistrer</button>
                    <button type="reset" class="btn-lg btn btn-clean font-weight-bold">Annuler</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--end::Actions-->
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@section('specific-js')
  <script type="text/javascript">
  // $('#kt_user_add_avatar').hide();


  // Class definition
  var KTSelect2 = function() {
    // Private functions
    var demos = function() {
      // basic
      $('#kt_select2_1').select2({
        placeholder: "Choisissez un Client"
      });

      // loading remote data
      function formatClient(client) {
        if (!client.nom) return client.text;
        return client.prenom+' '+client.nom.toUpperCase();
      }

      function formatClientSelection(client) {
        if(!client.nom) return client.text;
        $('#kt_user_add_avatar').hide();
        if(client.photo) {
          $('#kt_user_add_avatar').html(`<div class="image-input-wrapper" style="background-image: url(/storage/`+client.photo+`)"></div>`).show();
        } else {
          $('#kt_user_add_avatar').html(`<div class="image-input-wrapper" style="background-image: url(/assets/media/users/blank.jpg)"></div>`).show();
        }
        return client.prenom+' '+client.nom.toUpperCase();
      }

      $("#kt_select2_6").select2({
        placeholder: "Chercher un Client",
        allowClear: true,
        ajax: {
          url: "{{ route('json-list-comptes') }}",
          dataType: 'json',
          delay: 250,
          data: function(params) {
            return {
              q: params.term, // search term
              page: params.page || 1
            };
          },
          processResults: function(data, params) {
            params.page = params.page || 1;
            return {
              results: data.data,
              pagination: {
                more: (params.page * 30) < data.total_count
              }
            };
          },
          cache: true
        },
        escapeMarkup: function(markup) {
          return markup;
        }, // let our custom formatter work
        minimumInputLength: 1,
        templateResult: formatClient, // omitted for brevity, see the source of this page
        templateSelection: formatClientSelection // omitted for brevity, see the source of this page
      });

    }
    // Public functions
    return {
      init: function() {
        demos();
      }
    };
  }();

  // Initialization
  jQuery(document).ready(function() {
    KTSelect2.init();
  });


  </script>
@endsection